chore: :art: Add git commit-msg hook

diff --git a/common/git-hooks/commit-msg b/common/git-hooks/commit-msg
--- a/common/git-hooks/commit-msg
+++ b/common/git-hooks/commit-msg
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env sh
 #
 # This is an example Git hook for use with Rush.  To enable this hook, rename this file
 # to "commit-msg" and then run "rush install", which will copy it from common/git-hooks
@@ -16,10 +16,22 @@
 # an appropriate message if it wants to stop the commit.  The hook is allowed to edit
 # the commit message file.
 
+if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
+  echo ""
+  echo "Aborting commit. Your commit message is invalid. Use 'yarn cz' command." >&2
+  exit 1
+fi
+
 # This example enforces that commit message should contain a minimum amount of
 # description text.
-if [ `cat $1 | wc -w` -lt 3 ]; then
+if [ "$(cat $1 | wc -w)" -lt 3 ]; then
   echo ""
   echo "Invalid commit message: The message must contain at least 3 words."
-	exit 1
+  exit 1
+fi
+
+if ! head -1 "$1" | grep -qE "^.{1,93}$"; then
+  echo ""
+  echo "Aborting commit. Your commit message is too long." >&2
+  exit 1
 fi
